### ISSUE TITLE
Panic on DotnetCommand.Exec

### ISSUE THREAD

**Issue by kriive** [jfrog/jfrog-cli-core#1183]
This block does not check if the returned callbackFunc is `nil`.

https://github.com/jfrog/jfrog-cli-core/blob/670986eb89356adb1613216bb4348d39f479f52c/artifactory/commands/dotnet/dotnetcommand.go#L120-L122

**Comment by sverdlov93** [comment]
Hi @kriive 
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this.
This [PR](https://github.com/jfrog/jfrog-cli-core/pull/1184) should fix it.
I will update this thread once the next release will be out.
