### ISSUE TITLE
Invalid documentation link for build-info-extractor-jar

### ISSUE THREAD

**Issue by holysoles** [jfrog/jfrog-cli-core#1269]
### Describe the bug

When performing maven build actions with the jf cli tool, when the build-info-extractor jar isnt already present, there is a log message that refers to documentation around the behavior of this jar being downloaded.

However, that URL does not exist (anymore?) and redirects to [here](https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli), which doesn't contain any relevant information. The referred link also is not available on the wayback machine.

The link over [here in the documentation project](https://github.com/jfrog/documentation/blob/main/jfrog-applications/jfrog-cli/cli-for-jfrog-artifactory/package-managers-integration.md?plain=1#L36) is also old.

### Current behavior

> 19:02:37 [Info] The build-info-extractor jar is not cached locally. Downloading it now...
You can set the repository from which this jar is downloaded.
Read more about it at https://jfrog.com/help/r/jfrog-cli/downloading-the-maven-and-gradle-extractor-jars

### Expected behavior

A link to valid documentation, or even a PR so that I can better understand how to configure a CI pipeline to not need public internet access.

### JFrog CLI-Core version

dependency of jf cli

### JFrog CLI version (if applicable)

jf version 2.64.1

### Operating system type and version

jfrog/jfrog-cli-v2-jf:2.64.1

**Comment by RobiNino** [comment]
Hi @holysoles ,
Thanks for letting us know. The documentation is available [here](https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli/cli-for-jfrog-artifactory/package-managers-integration#downloading-the-maven-and-gradle-extractor-jars).

**Comment by holysoles** [comment]
@RobiNino Thank you! I can close this issue if appropriate based on the PR getting merged

**Comment by RobiNino** [comment]
The fix is merged and released, you can close, thanks
