### ISSUE TITLE
add Xray scan id to SARIF output

### ISSUE THREAD

**Issue by deekue** [jfrog/jfrog-cli-core#1278]
**Is your feature request related to a problem? Please describe.**

the scan id is included in `--format=json` but not in `--format sarif`

```shell
$ jq -r '.[].scan_id' ./xray.json 
0d0a1fd8-ece8-4e2a-6be4-f59edf917227
```
```shell
$ jq -r '.runs[].automationDetails.guid' ./xray-sarif.json
null
```

the scan id is used to access the On-Demand Scanning report. e.g.  
https://artifactory.example.com/ui/onDemandScanning/0d0a1fd8-ece8-4e2a-6be4-f59edf917227

some scans take a long time so running them twice to get both the SARIF output and the scan id is less than ideal.

**Describe the solution you'd like to see**

output the scan id in the [guid field](https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790777) of the [automationDetails object](https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790773) for each run object

**Describe alternatives you've considered**

Selling all my worldly possessions and retreating into the forest.

**Additional context**
[SARIF v2.1.0](https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html)

**Comment by eyalbe4** [comment]
@deekue,
Thanks for creating this feature request.
I recommend however that you open this feature request under
github.com/jfrog/jfrog-cli-security
and close this one, so that it receives more visibility.

**Comment by deekue** [comment]
thanks, I created a new issue
https://github.com/jfrog/jfrog-cli-security/issues/199
