### ISSUE TITLE
.NET Project dependencies not found when project is not located under solution directory

### ISSUE THREAD

**Issue by prochnowc** [jfrog/jfrog-cli-core#382]
**Describe the bug**
If the .NET project file is not located in a directory below the solution file no dependencies are found.

**To Reproduce**
Create a project with the following directory layout:
- tmp\solution.sln
- project1\project1.csproj

Run the JFrog CLI to record the dependencies when packages are restored. "jfrog dotnet restore tmp\solution.sln --build-name test --build-number 1"
project1 is reported with "Project dependencies was not found for project"

**Expected behavior**
I expect that dependencies are found.

**Versions**
- JFrog CLI version (if applicable): 2.15.1

**Comment by eyalbe4** [comment]
@prochnowc ,
Thanks for reporting this issue.
Will you be able to share a smaple project on GitHub that reproduces this issue?

**Comment by prochnowc** [comment]
[jfrog-cli-issue.zip](https://github.com/jfrog/jfrog-cli-core/files/8560423/jfrog-cli-issue.zip)

To reproduce change to the "jfrog-cli-issue" directory and run the following commands:

```
$env:JFROG_CLI_LOG_LEVEL="DEBUG"
jfrog dotnet-config
jfrog dotnet restore .\solutions\test.sln --build-name test --build-number 1
```

You will see the message `[Debug] Project dependencies was not found for project: project1` and dependencies are not recorded in the build info.

BTW.. i'm running this on Windows, dont know if linux works.

**Comment by prochnowc** [comment]
@eyalbe4 I want to mention that this issue is blocking us from obtaining proper build info's. We have a pro-x license for Artifactory. Thank you.

**Comment by eyalbe4** [comment]
@prochnowc,
Just updating that this task is included in our work plan, We'll share here an update once this is implemented.

**Comment by prochnowc** [comment]
@eyalbe4 Thanks for fixing this issue. May I ask when it gets released?

**Comment by gailazar300** [comment]
@prochnowc Jfrog CLI v2.18.0 is out with this issue fix.
We would appreciate it if you could give it a try, and let us know if it works as aspected.

**Comment by prochnowc** [comment]
@gailazar300 Thanks for the fix. It works now.
