### ISSUE TITLE
log message _Deleting 0xc27ae0 files_ with `rt git-lfs-clean`

### ISSUE THREAD

**Issue by rico-chet** [jfrog/jfrog-cli-core#587]
### Describe the bug

Weird log message is presented to the user when running `rt git-lfs-clean`

### Current behavior

User sees a message starting with _Deleting 0xc27ae0 files from_, note the hexadecimal notation.

### Reproduction steps

1. Run `JFROG_CLI_LOG_LEVEL=INFO jf rt git-lfs-clean` with sensible parameters in a sensible environment
2. Among other messages, find in the log:
> Deleting 0xc27ae0 files

### Expected behavior

A sensible message, e.g.:
> Deleting 1 files

### JFrog CLI-Core version

2.23.0

### JFrog CLI version (if applicable)

2.28.0

### Operating system type and version

Debian Linux 11

**Comment by sverdlov93** [comment]
Hi @rico-chet,
Thanks for reporting this issue.
This PR - https://github.com/jfrog/jfrog-cli-core/pull/588 should fix it.
I will update this thread once the next release will be out.

**Comment by sverdlov93** [comment]
Hi @rico-chet,
[JFrog CLI 2.28.1](https://github.com/jfrog/jfrog-cli/releases/tag/v2.28.1) is released and should fix the above issue.
Looking forward to your feedback on it.

**Comment by rico-chet** [comment]
Confirm that the issue is fixed:

>09:35:43 [��Info] Found 0 files to keep, and 1 to clean
>09:35:43 [��Info] Deleting 1 files from rico_chets_repository ...
